name: Constant Integration and Constant Deployment
on:
  push:
  create:
  delete:
  deployment:
  fork:
  merge_group:
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Executing Remote SSH Commands Using Password
      uses: appleboy/ssh-action@v0.1.2 #Marketplace Tool
      with:
        host: ${{secrets.SSH_HOST}} # IP address
        key: ${{secrets.SSH_KEY}} # Private key
        username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
        script: |
          cd /var/www/html
          current_branch=$(git rev-parse --abbrev-ref HEAD); 
          git fetch -p && for branch in $(git for-each-ref --format '%(refname) %(upstream:track)' refs/heads | awk '$2 == "[gone]" {sub("refs/heads/", "", $1); print $1}'); do git branch -D $branch; done
          for remote in $(git branch -r | grep -v '\->' | sed "s,\x1B\[[0-9;]*[a-zA-Z],,g" | cut -d '/' -f 2-); do git checkout -B $remote origin/$remote; git reset --hard; git pull origin $remote; done; 
          git checkout $current_branch
